branches:
  only:
  - "/^v[0-9]/"
env:
  global:
  - AWS_REGION: us-west-2
  - secure: wrUAn1phU0aUINzimgc0gHv8qU4n9j1lBiloaLzNVWrTHSXlkg8qhKlIDG/Z/g5Ln/z6lGQEvOaloBFEG6nRFANgxrEC8QKUNFIrEr2R/serpb41moEWZc4pqOMlwS5jG9ObFs3pg2v9soGxeNKs7hxpG0jVj0vX1OwaGhpc7wmVyeJd5ir6C5zHnpauPhsucfe86tnb0DqvDd0hpDGx+fOdYzb0OdPIye7LwEAmEJenwaeL8aGR4TnFGyr5WbXPra0ae3sgmjKT1sU3yFYi/L5lnlceiLddNWXN6UNZxWA5qsuSpAavw7gLUE5pgYRIr6C3N8NutCm06nqvfpBNwzmPDa+7v7d3SleJYfP1gcoLq2bAtA0miPHRiydSLbpv110kyYLz9qsnQC11ENgwfxZMTveVM2rRyO7dH6tVF3efHE8Fz63RZAHgmtBswVTyOR1I1eAQ28aB7u0hF3fBGpCvyNW81ZaO4jfBKoot+Qqr0p7Ka8/WmzWTD9n7h1/g1d45UgFSQrhAi/ziyFeXwhFr1BzSaiXYnzUcNKf9udA6Mh4oH1K0Ruy706w/cOtQ2F7CIgbcoVrWVf8OIMbvPd5PqHUGPgIRHwTroKD7aXY4VEtAzZrL7MuV8z5hPnx46jCpxicSBsyYXaEGlif8J2Fd6S23u3d8KUydOHgJnmc=
  - secure: mRuMUp5qdQPcEo1OBKB3mzkOgtSmDkAT0qzDITrniCrG7jxes9ITXgMZiuNjxSYGSrEw8DPvZPcE5ehuQL238wCzR2os+MZLnl1hTIa/rMIWSXvJdHhreBLFJNULrjO1yWTWf34YmwPi2j7HxI4jpwIAO8oZmhmo4NzeWh7nHHy8vrl8vzN9omCm3aAudkWV4mBBxPlo+DmqhB4woTGCKIfYiH1JMUmzitDCJZ77qvUbE8ZdTSfp+yRON7LuLH7NMtECZOXeZDN8ZDLHQaHtU3okjrLqGtr6xnZccuhDo+oVOpDZKLkn95J5ftRAHneYIr/ek1CGgF2KFOwDKU6c+nReXspW+fVv39jdruRiskki4rbK0mHZYIlgp8A0ZszYQGk4rpDaaoHFouwtuZRLxpJ9vmLp8Fj2UlHC1Pr+7fESpVhDuB6xVDac6slKGF4Cp84+m+Qkfs96ZZdORfmXwjaSNzg6tN+4hrTjtyHU89X2WPVxZVwhQTyr/L99NOBHlyO0bRw5Fahw7a6Hyyw1N8hsIWgcfvBvm4jlQCV9GPKmMrspP+PC+XCeRdAfd0JKMtIONh2idSMDo8IHeLE42zfev/KjzFv4M3FwEXa0v1YlSLfE1zvUU925qiYVSaBectwI0TAutK1d3NxP0MY2s7uVajdIYPAU8/ItMsic2qQ=
  - secure: DGpMBmexEP/dNi62nf43slxlAZU8C0w8kZ8g+jF3G/9gmQWa8YdQextrL0heIDQ8X4Zv1PA52MBLoOsT1MhhqIRDnNYCoYIijRADUsVCVEHF+3ofqhH9ix4iw+kOnKglXXCvBoZlFSLGiEpJv1Q08UFuVC6h/sn8M6vsRSdpG3gOf1Lhals+p2MXIV3R8Pr240Zkbol9tIeIUDqB5H1DUAgFt+pGa6Qs9TDAQk8OZ3iiGsvGamyGmzj/dUGmJe7lh0GbMqRZJhKiFW4tJtJ4Op0o8JnUd58+WeJbtaz90GtdR0it4dusl58RVGXTVuALByl1Lik86DSYDcRAl5K3zVBazJVItfw/2VQDMbTBwwZAleHhn4Ar2d0/DlXwJfizac+SlRmtK89SrO61OBPHLZVeYSpp6+6Fx3fyAPKKbXX3f2/FFVnLsasJH5X7bEH2DRUA5YDPZtYeJlcOMTrNNMsKkIf29tNukPTLilQox+Y7FLDYP8y8qCXxTSL9SeWbVghesbwYO+YTca0ihyfr1v2PZqEItWWK3WLSYTjDSJjoA2RSYr9RYK814VrHYVqEGMmY5ogOtARNo73AVktc6GupTTXFux7Qa3G202LAKGuif13TQkUWPPUp5B8hthXDlObUfAIFKu2kcgfYaW+kEWRV9E2bXBClcc3p/HyOkrs=
  - secure: EHVOrr78YQYyXDRJHZFaUnfuPlN1E12hF8Ozr/9VfOhMAqhl1SeW3ynN38BoE3kpYrnVR5JrVer2/YGzQuvZrXdozxMwlUk42TmvMCSVIoq4dSEPh9VqZheVgSCTbOJQH80W3HTTa8wDM23sIIzAp+77o6dOidN9xi0agx512vsr/pus4b8dfK7r8kdsYaZj6GrM/7BsbyTMJ2kvB2dXQ38kCNZZmni3q0qx70Bk9Jl70XHb3YCfcKPvkmqEd/Q93PO4DgLOd2xujWVftwZOAJnu7MOGeWt1/5ysWKrD/YVt+VehSurNNY/GFP9ojvgHV7YP5BZ1DAOHOSraGDzoElOShKuz+ClI1r0lIr6z+U9g0/g85twikdO4jD0JRRXKXr5Ed6m7Uly10HFk7JIeacvMQa2miRa3UI6hdExpT+NgEXhIag0pYTdPfEWYxap6XTL3zglmRKyYRsdEwQtR/EQceAn8NaGTCidQHfDDoug4u5dBqQ4O5t5MVfgrst3SylfWu9pXnhU6t9MyAC8DbnyRkffLs+cVaYx+iWXGQJCQn6BJ6Bs2IDVTslexhaC5USXt8RjHq2Tsx24B3kLsKw+8UTAiQ0Q48M2jh0KCwu21xsiXvR8ZArB2Akcd0vmeGBxpvTE9PwWuB6Pv1UmkMGiJTDXUzYNTiqd7oTN9R0M=
matrix:
  include:
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-armv7
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/meshblu-connector-builder:linux-armv7 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian --destination-path=/usr/local/bin \
            && meshblu-connector-uploader-github \
            && /work/upload-deb-s3 \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x86
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/meshblu-connector-builder:linux-x86 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian --destination-path=/usr/local/bin \
            && meshblu-connector-uploader-github \
            && /work/upload-deb-s3 \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x64
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/meshblu-connector-builder:linux-x64 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian --destination-path=/usr/local/bin \
            && meshblu-connector-uploader-github \
            && /work/upload-deb-s3 \
          '
  - os: osx
    node_js: '8'
    language: node_js
    after_success:
    - yarn global add meshblu-connector-pkger meshblu-connector-installer-macos meshblu-connector-uploader-github
    - |
      meshblu-connector-pkger \
      && meshblu-connector-installer-macos --destination-path=/Library/MeshbluConnectors/bin \
      && meshblu-connector-uploader-github
